/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * application.java
 *
 * Created on 13 févr. 2012, 12:16:58
 */
package menu;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author khalid
 */

public class application extends javax.swing.JFrame {
    Fichier f = new Fichier();

    /** Creates new form application */
    public application() {
        initComponents();
        
        panelCours.setVisible(false);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCours = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        coursIntroduction = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursTitre = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuNouveauCours = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        menuOuvrir = new javax.swing.JMenuItem();
        menuEnregistrer = new javax.swing.JMenuItem();
        menuEnregistrerSous = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        coursIntroduction.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                coursIntroductionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                coursIntroductionKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(coursIntroduction);

        coursTitre.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        coursTitre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                coursTitreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                coursTitreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                coursTitreKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(coursTitre);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Titre : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Introduction : ");

        javax.swing.GroupLayout panelCoursLayout = new javax.swing.GroupLayout(panelCours);
        panelCours.setLayout(panelCoursLayout);
        panelCoursLayout.setHorizontalGroup(
            panelCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCoursLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(53, 53, 53)
                .addGroup(panelCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelCoursLayout.setVerticalGroup(
            panelCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCoursLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(panelCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jMenu1.setBackground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("File");

        jMenu3.setText("Nouveau");

        menuNouveauCours.setText("cours                                 ");
        menuNouveauCours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNouveauCoursActionPerformed(evt);
            }
        });
        jMenu3.add(menuNouveauCours);

        jMenu5.setText("Exercice");

        jMenuItem2.setText("Execice de closure");
        jMenu5.add(jMenuItem2);

        jMenuItem9.setText("QCM");
        jMenu5.add(jMenuItem9);

        jMenuItem10.setText("Phtase en désordre");
        jMenu5.add(jMenuItem10);

        jMenuItem11.setText("Mots Croisés");
        jMenu5.add(jMenuItem11);

        jMenuItem12.setText("Metre en Relation");
        jMenu5.add(jMenuItem12);

        jMenuItem13.setText("Quiz à Plusieurs Reponses correctes");
        jMenu5.add(jMenuItem13);

        jMenu3.add(jMenu5);

        jMenu1.add(jMenu3);

        menuOuvrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuOuvrir.setBackground(new java.awt.Color(51, 51, 51));
        menuOuvrir.setText("Ouvrir      ");
        menuOuvrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOuvrirActionPerformed(evt);
            }
        });
        jMenu1.add(menuOuvrir);

        menuEnregistrer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuEnregistrer.setText("Enregistrer");
        menuEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEnregistrerActionPerformed(evt);
            }
        });
        jMenu1.add(menuEnregistrer);

        menuEnregistrerSous.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuEnregistrerSous.setText("Enregistrer-sous");
        menuEnregistrerSous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEnregistrerSousActionPerformed(evt);
            }
        });
        jMenu1.add(menuEnregistrerSous);

        jMenu4.setText("Imprimer");

        jMenuItem5.setText("Numerique");
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Imprimer");
        jMenu4.add(jMenuItem6);

        jMenu1.add(jMenu4);

        jMenuItem8.setText("Quiter");
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void menuOuvrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOuvrirActionPerformed
    f.ouvrirFichier(coursTitre, coursIntroduction);
    panelCours.setVisible(true);
}//GEN-LAST:event_menuOuvrirActionPerformed

private void coursTitreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coursTitreKeyPressed
                  
      
}//GEN-LAST:event_coursTitreKeyPressed

private void coursIntroductionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coursIntroductionKeyPressed

}//GEN-LAST:event_coursIntroductionKeyPressed

private void coursTitreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coursTitreKeyTyped

}//GEN-LAST:event_coursTitreKeyTyped

private void coursTitreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coursTitreKeyReleased
    f.setTitre(coursTitre.getText());
}//GEN-LAST:event_coursTitreKeyReleased

private void menuNouveauCoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNouveauCoursActionPerformed
      panelCours.setVisible(true);
      coursTitre.setText("");
      coursIntroduction.setText("");
}//GEN-LAST:event_menuNouveauCoursActionPerformed

private void coursIntroductionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coursIntroductionKeyReleased
      f.setIntroduction(coursIntroduction.getText());
}//GEN-LAST:event_coursIntroductionKeyReleased

private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

}//GEN-LAST:event_formWindowClosed

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      f.deleteTemp();
}//GEN-LAST:event_formWindowClosing

private void menuEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEnregistrerActionPerformed
    f.enregistrerFichier();
}//GEN-LAST:event_menuEnregistrerActionPerformed

private void menuEnregistrerSousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEnregistrerSousActionPerformed
    f.enregistrerSousFichier();
}//GEN-LAST:event_menuEnregistrerSousActionPerformed


    /**
     * @param args the command line arguments
     */
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new application().setVisible(true);
            }
        });
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane coursIntroduction;
    private javax.swing.JTextPane coursTitre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem menuEnregistrer;
    private javax.swing.JMenuItem menuEnregistrerSous;
    private javax.swing.JMenuItem menuNouveauCours;
    private javax.swing.JMenuItem menuOuvrir;
    private javax.swing.JPanel panelCours;
    // End of variables declaration//GEN-END:variables
}
